name: Precheck using AI prediction
on: [push, pull_request]
jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run prediction (example)
        run: |
          python src/generate_sample_data.py
          python src/train_model.py --data data/ci_sample.csv --out model/model.pkl
          python -c "import joblib; m=joblib.load('model/model.pkl'); print('predict ok')"
